version : '3'

services: 
  magento2:
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - ../:/var/www/html/:cached
  ingress:
    volumes: *appvolumes
volumes: 
  appdata:
