version : '3'

services: 
  magento2:
    volumes: &appvolumes
      - appdata:/var/www/html
      - ~/.composer:/var/www/.composer:delegated
      - ../app:/var/www/html/app:cached
      - ../bin:/var/www/html/bin:cached
      - ../dev:/var/www/html/dev:cached
      - ../lib:/var/www/html/lib:cached
      - ../pub:/var/www/html/pub:delegated
      - ../setup:/var/www/html/setup:cached
      - ../update:/var/www/html/update:cached
      - ../patches:/var/www/html/patches:cached
      - ../index.php:/var/www/html/index.php:cached
      - ../mage2docker-modules:/var/www/html/mage2docker-modules:cached
      - ../nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ../composer.json:/var/www/html/composer.json:delegated
      - ../composer.lock:/var/www/html/composer.lock:delegated
  ingress:
    volumes: *appvolumes
volumes: 
  appdata:
